name: Regenerate PluginMaster
on: 
  push:
    branches:
      - cn-api4
  workflow_dispatch:

jobs:
  generate:
    name: Regenerate PluginMaster
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-python@v2
        with:
            python-version: '3.8'
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Generate PluginMaster
        run: pip install requests && python generate_pluginmaster.py
      - name: Commit files
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Regenerate PluginMaster"
      - name: Push changes
        continue-on-error: false
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
